server:
  port: 8080
spring:
  profiles:
    include:
      - default
      - local
      - dev
      - integration
      - stg
      - prod
  jpa:
    open-in-view: false

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

couchbase:
  connection-string: ENC(Il6lCfMZJx6CUSrTRUeihEb5aJzuD5vno21sisl8f3FQHhVXWZwjBg==)
#  connection-string: ENC(Qp9iMFzXOstAUc2b9KNItwxUloO85ciyymNXt9Sxvx0=)
  username: ENC(nBzV1KeBwgKxwGiUxaVX/mlNcV69mtP1)
  password: ENC(OVGKDlSCauyWNaLjs/+iA7uV2vxFFzDs)
  bucket-abuse-log:
    name: abuse-log
    user-name: dev-admin
    password: dev-admin
  bucket-abuse:
    name: abuse
    user-name: dev-admin
    password: dev-admin
  bucket-abuse-limit:
    name: abuse-limit
    user-name: dev-admin
    password: dev-admin

logging:
  level:
    org.springframework.data: INFO
