server:
  port: 8080
spring:
  profiles:
    include:
      - default
      - local
      - dev
      - prod
  jpa:
    open-in-view: false
  rabbitmq:
    host: ENC(K0R56cr7C52XtbdnKMczhpyVEmk4ud8K)
    port: 5672
    username: ENC(RyBm0pzeuZJYJkE9To/6DA==)
    password: ENC(OV6yk8pEddLU0FfK9ByziJEuLKN4dzMi)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

couchbase:
#  connection-string: ENC(Il6lCfMZJx6CUSrTRUeihEb5aJzuD5vno21sisl8f3FQHhVXWZwjBg==)
  connection-string: ENC(Qp9iMFzXOstAUc2b9KNItwxUloO85ciyymNXt9Sxvx0=)
  username: ENC(nBzV1KeBwgKxwGiUxaVX/mlNcV69mtP1)
  password: ENC(OVGKDlSCauyWNaLjs/+iA7uV2vxFFzDs)
  bucket-abuse-log:
    name: abuse_log
    user-name: ENC(/8bBBRalNsIJMf8SpkAma9OMy+YGnnHa)
    password: ENC(JLA3+d6AiRDRvob0jgIM0aV2d5X8lw8R)
  bucket-abuse-rule:
    name: abuse_rule
    user-name: ENC(afBFdIW2E88Bn2I7qt31oPRGkdCu8QIG)
    password: ENC(JwBAtf9XXlQsFi/UZ98UPjj2b8oqN2tU)
  bucket-abuse-limit:
    name: abuse_limit
    user-name: ENC(x1VEuHwGL6ytaJImxk7ZkT6jUqxIUTDP)
    password: ENC(93wqqZ9Gpug60fZc5TqO1OoBuVp1VCfb)

rabbitmq:
  queue.name: abuse.queue
  exchange.name: abuse.exchange
  routing.key: totoro

logging:
  level:
    org.springframework.data: INFO
