server:
  port: 8080
spring:
  profiles:
    include:
      - default
      - local
      - dev
      - integration
      - stg
      - prod
  jpa:
    open-in-view: false


couchbase:
  connection-string: couchbase://10.250.25.16
  username: dev-admin
  password: dev-admin
  bucket-abuse-log:
    name: abuse-log
    user-name: dev-admin
    password: dev-admin
  bucket-abuse:
    name: abuse
    user-name: dev-admin
    password: dev-admin
  bucket-abuse-limit:
    name: abuse-limit
    user-name: dev-admin
    password: dev-admin

logging:
  level:
    org.springframework.data: INFO