server:
  port: 8080
spring:
  profiles:
    include:
      - default
      - local
      - dev
      - integration
      - stg
      - prod
  jpa:
    open-in-view: false

couchbase:
  connection-string: couchbase://127.0.0.1
  username: dev-admin
  password: dev-admin
  bucket-abuse-log:
    name: abuse_log
    user-name: dev-admin
    password: dev-admin
  bucket-abuse:
    name: abuse
    user-name: dev-admin
    password: dev-admin

